# Generated by Django 6.0.7 on 2026-07-30 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='nombre')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de aparición en listas y catálogo', verbose_name='orden')),
            ],
            options={
                'verbose_name': 'categoría',
                'verbose_name_plural': 'categorías',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='nombre')),
                ('codigo', models.CharField(help_text='Código de 3 letras usado en el SKU, p. ej. BEL, KRO, LYN.', max_length=3, unique=True, verbose_name='código')),
                ('notas', models.CharField(blank=True, max_length=255, verbose_name='notas')),
            ],
            options={
                'verbose_name': 'marca',
                'verbose_name_plural': 'marcas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='LineaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='nombre')),
                ('codigo', models.CharField(help_text='Código corto usado en el SKU, p. ej. MASC, CHED, JPAV. No cambia.', max_length=4, unique=True, verbose_name='código')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineas', to='catalogo.categoria', verbose_name='categoría')),
            ],
            options={
                'verbose_name': 'línea de producto',
                'verbose_name_plural': 'líneas de producto',
                'ordering': ['categoria__orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, help_text='Se genera solo al guardar por primera vez. No editar después.', max_length=32, unique=True, verbose_name='SKU')),
                ('contenido_neto', models.DecimalField(blank=True, decimal_places=2, help_text=' ', max_digits=9, null=True, verbose_name='contenido neto')),
                ('unidad_contenido', models.CharField(blank=True, choices=[('kg', 'kg'), ('ml', 'ml'), ('pza', 'pza')], max_length=3, verbose_name='unidad')),
                ('forma', models.CharField(blank=True, choices=[('BAR', 'Barra'), ('RUE', 'Rueda'), ('REB', 'Rebanado'), ('POR', 'Porción'), ('CUN', 'Cuña')], max_length=3, verbose_name='forma')),
                ('tipo_precio', models.CharField(choices=[('pieza', 'Por pieza'), ('kilo', 'Por kilo')], max_length=10, verbose_name='tipo de precio')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio')),
                ('proveedor_1', models.CharField(blank=True, max_length=150, verbose_name='proveedor 1')),
                ('proveedor_2', models.CharField(blank=True, max_length=150, verbose_name='proveedor 2')),
                ('requiere_produccion', models.BooleanField(default=False, help_text='Se rebana o porciona en casa', verbose_name='requiere producción')),
                ('tipo_almacenamiento', models.CharField(blank=True, choices=[('seco', 'Seco'), ('frio', 'Frío'), ('congelado', 'Congelado')], max_length=10, verbose_name='almacenamiento')),
                ('disponible_para_pedido', models.BooleanField(default=True, verbose_name='disponible para pedido')),
                ('notas', models.CharField(blank=True, max_length=255, verbose_name='notas')),
                ('visible_para_clientes', models.BooleanField(default=False, verbose_name='visible para clientes')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='imagen')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('linea', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='catalogo.lineaproducto', verbose_name='línea')),
                ('marca', models.ForeignKey(blank=True, help_text=' ', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='catalogo.marca', verbose_name='marca')),
                ('producido_de', models.ForeignKey(blank=True, help_text='Producto base del que sale, p. ej. CHEDAR REBANADO ← CHEDAR BARRA', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salidas_produccion', to='catalogo.producto', verbose_name='producido a partir de')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'ordering': ['linea__categoria__orden', 'linea__nombre', 'marca__nombre'],
                'indexes': [models.Index(fields=['linea', 'marca'], name='catalogo_pr_linea_i_72250d_idx'), models.Index(fields=['disponible_para_pedido', 'visible_para_clientes'], name='catalogo_pr_disponi_3193d7_idx')],
                'constraints': [models.UniqueConstraint(fields=('linea', 'marca', 'contenido_neto', 'unidad_contenido', 'forma'), name='variante_producto_unica')],
            },
        ),
    ]
