# Generated by Django 6.0.7 on 2026-07-31 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_convertir_kg_a_gramos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='vida_anaquel',
            field=models.IntegerField(verbose_name='días anaquel'),
        ),
    ]
