# Generated by Django 6.0.7 on 2026-08-06 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_alter_producto_vida_anaquel'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='unidades_por_empaque',
            field=models.IntegerField(blank=True, default=1, help_text='Cantidad de unidades por empaque o caja.', verbose_name='unidades por empaque'),
        ),
    ]
