# Generated by Django 6.0.7 on 2026-08-14 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_producto_unidades_por_empaque'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoBarras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('codigo', models.CharField(db_index=True, help_text='Tal como viene impreso en el empaque. Se guarda sin espacios ni guiones.', max_length=32, unique=True, verbose_name='código')),
                ('simbologia', models.CharField(choices=[('ean13', 'EAN-13'), ('ean8', 'EAN-8'), ('upca', 'UPC-A'), ('itf14', 'ITF-14 (caja)'), ('code128', 'Code 128'), ('otro', 'Otro')], default='ean13', max_length=10, verbose_name='simbología')),
                ('nivel_empaque', models.CharField(choices=[('pieza', 'Pieza'), ('caja', 'Caja')], default='pieza', max_length=10, verbose_name='nivel de empaque')),
                ('unidades', models.PositiveIntegerField(default=1, help_text='Cuántas piezas representa un escaneo de este código. 1 si es la pieza suelta.', verbose_name='unidades por escaneo')),
                ('principal', models.BooleanField(default=False, help_text='El que se usa al mostrar un solo código del producto. Uno por producto.', verbose_name='principal')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos_barras', to='catalogo.producto', verbose_name='producto')),
            ],
            options={
                'verbose_name': 'código de barras',
                'verbose_name_plural': 'códigos de barras',
                'ordering': ['producto', '-principal', 'codigo'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('principal', True)), fields=('producto',), name='codigo_barras_principal_unico_por_producto')],
            },
        ),
    ]
