# Generated by Django 6.0.7 on 2026-07-31 21:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0004_alter_producto_vida_anaquel'),
        ('compras', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('clave', models.CharField(help_text='Código corto para identificar el almacén, p. ej. ALM-01.', max_length=10, unique=True, verbose_name='clave')),
                ('tipo_temperatura', models.CharField(choices=[('seco', 'Seco'), ('frio', 'Frío'), ('congelado', 'Congelado')], help_text='Régimen de temperatura de este almacén.', max_length=10, verbose_name='temperatura de almacenamiento')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'verbose_name': 'almacén',
                'verbose_name_plural': 'almacenes',
                'ordering': ['clave'],
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('codigo', models.CharField(blank=True, help_text='Se genera solo al guardar por primera vez. No editar después.', max_length=48, verbose_name='código')),
                ('codigo_proveedor', models.CharField(blank=True, help_text='Lote/lote tal como lo identifica el proveedor.', max_length=50, verbose_name='código del proveedor')),
                ('fecha_caducidad', models.DateField(verbose_name='fecha de caducidad')),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='costo unitario')),
                ('cantidad_inicial', models.DecimalField(decimal_places=3, help_text='Cantidad con la que se creó el registro (normalmente 0: el lote crece vía movimientos).', max_digits=12, verbose_name='cantidad inicial')),
                ('cantidad_actual', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='cantidad actual')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='inventario.almacen', verbose_name='almacén')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='catalogo.producto', verbose_name='producto')),
            ],
            options={
                'verbose_name': 'lote',
                'verbose_name_plural': 'lotes',
                'ordering': ['fecha_caducidad', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('tipo', models.CharField(choices=[('entrada_compra', 'Entrada por compra'), ('salida_venta', 'Salida por venta'), ('ajuste_positivo', 'Ajuste positivo'), ('ajuste_negativo', 'Ajuste negativo'), ('merma', 'Merma'), ('caducado', 'Caducado'), ('devolucion', 'Devolución a proveedor')], max_length=20, verbose_name='tipo')),
                ('cantidad', models.DecimalField(decimal_places=3, help_text='Con signo: positiva para entradas, negativa para salidas. El tipo no fuerza el signo.', max_digits=12, verbose_name='cantidad')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha')),
                ('notas', models.CharField(blank=True, max_length=255, verbose_name='notas')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventario.lote', verbose_name='lote')),
                ('recepcion_detalle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='compras.recepciondetalle', verbose_name='detalle de recepción')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_inventario', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'movimiento de inventario',
                'verbose_name_plural': 'movimientos de inventario',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddIndex(
            model_name='lote',
            index=models.Index(fields=['producto', 'almacen'], name='inventario__product_7c894f_idx'),
        ),
        migrations.AddIndex(
            model_name='lote',
            index=models.Index(fields=['fecha_caducidad'], name='inventario__fecha_c_6ef501_idx'),
        ),
        migrations.AddConstraint(
            model_name='lote',
            constraint=models.UniqueConstraint(fields=('producto', 'almacen', 'codigo'), name='lote_unico_producto_almacen_codigo'),
        ),
    ]
