# Generated by Django 6.0.7 on 2026-08-17 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_codigobarras'),
        ('inventario', '0002_movimientoinventario_surtido_detalle'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstandarInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('cantidad_minima', models.DecimalField(decimal_places=3, help_text='Punto de reorden: por debajo de esto hay que pedir.', max_digits=12, verbose_name='mínimo')),
                ('cantidad_objetivo', models.DecimalField(decimal_places=3, help_text='Hasta dónde subir cuando se pide. Nunca menor al mínimo.', max_digits=12, verbose_name='objetivo')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('notas', models.CharField(blank=True, max_length=255, verbose_name='notas')),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estandares', to='inventario.almacen', verbose_name='almacén')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estandares', to='catalogo.producto', verbose_name='producto')),
            ],
            options={
                'verbose_name': 'estándar de inventario',
                'verbose_name_plural': 'estándares de inventario',
                'ordering': ['almacen', 'producto'],
                'indexes': [models.Index(fields=['almacen', 'activo'], name='inventario__almacen_5060de_idx')],
                'constraints': [models.UniqueConstraint(fields=('producto', 'almacen'), name='estandar_unico_producto_almacen'), models.CheckConstraint(condition=models.Q(('cantidad_objetivo__gte', models.F('cantidad_minima'))), name='estandar_objetivo_no_menor_al_minimo')],
            },
        ),
    ]
