# Generated by Django 6.0.7 on 2026-08-06 04:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0005_producto_unidades_por_empaque'),
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('nombre_comercial', models.CharField(max_length=150, verbose_name='nombre comercial')),
                ('razon_social', models.CharField(blank=True, max_length=200, verbose_name='razón social')),
                ('rfc', models.CharField(blank=True, max_length=13, verbose_name='RFC')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='correo')),
                ('telefono_restaurante', models.CharField(blank=True, max_length=20, verbose_name='teléfono del restaurante')),
                ('direccion_entrega', models.TextField(blank=True, verbose_name='dirección de entrega')),
                ('nombre_chef', models.CharField(blank=True, max_length=150, verbose_name='nombre del chef')),
                ('whatsapp_chef', models.CharField(blank=True, max_length=20, verbose_name='WhatsApp del chef')),
                ('encargado_pedidos', models.CharField(blank=True, max_length=150, verbose_name='encargado de pedidos')),
                ('whatsapp_encargado_pedidos', models.CharField(blank=True, max_length=20, verbose_name='WhatsApp del encargado de pedidos')),
                ('pide_lunes', models.BooleanField(default=False, verbose_name='lunes')),
                ('pide_martes', models.BooleanField(default=False, verbose_name='martes')),
                ('pide_miercoles', models.BooleanField(default=False, verbose_name='miércoles')),
                ('pide_jueves', models.BooleanField(default=False, verbose_name='jueves')),
                ('pide_viernes', models.BooleanField(default=False, verbose_name='viernes')),
                ('pide_sabado', models.BooleanField(default=False, verbose_name='sábado')),
                ('dias_credito', models.PositiveSmallIntegerField(default=0, verbose_name='días de crédito')),
                ('limite_credito', models.DecimalField(blank=True, decimal_places=2, help_text='Vacío significa sin límite definido; 0 significa solo contado.', max_digits=10, null=True, verbose_name='límite de crédito')),
                ('tarea_pendiente', models.TextField(blank=True, help_text='Algo que va a cambiar y hay que atender.', verbose_name='tarea')),
                ('anotaciones', models.TextField(blank=True, verbose_name='anotaciones')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ['nombre_comercial'],
            },
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='nombre')),
                ('clave', models.CharField(help_text='Código corto para identificar la ruta, p. ej. RT-01.', max_length=10, unique=True, verbose_name='clave')),
                ('activa', models.BooleanField(default=True, verbose_name='activa')),
            ],
            options={
                'verbose_name': 'ruta',
                'verbose_name_plural': 'rutas',
                'ordering': ['clave'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('folio', models.CharField(blank=True, help_text='Se genera solo al guardar por primera vez. No editar después.', max_length=20, verbose_name='folio')),
                ('fecha_pedido', models.DateField(default=django.utils.timezone.localdate, verbose_name='fecha del pedido')),
                ('fecha_entrega_estimada', models.DateField(blank=True, null=True, verbose_name='fecha de entrega estimada')),
                ('estatus', models.CharField(choices=[('borrador', 'Borrador'), ('confirmado', 'Confirmado'), ('surtido_parcial', 'Surtido parcial'), ('surtido', 'Surtido'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='borrador', max_length=20, verbose_name='estatus')),
                ('notas', models.TextField(blank=True, verbose_name='notas')),
                ('almacen_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='inventario.almacen', verbose_name='almacén origen')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='pedidos.cliente', verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
                'ordering': ['-fecha_pedido', '-folio'],
            },
        ),
        migrations.CreateModel(
            name='PedidoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('cantidad_pedida', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='cantidad pedida')),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Fotografía al momento del pedido.', max_digits=10, verbose_name='precio unitario')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='pedidos.pedido', verbose_name='pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_pedido', to='catalogo.producto', verbose_name='producto')),
            ],
            options={
                'verbose_name': 'detalle de pedido',
                'verbose_name_plural': 'detalles de pedido',
                'ordering': ['pedido', 'producto'],
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='ruta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='pedidos.ruta', verbose_name='ruta'),
        ),
        migrations.CreateModel(
            name='Surtido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('fecha_surtido', models.DateField(default=django.utils.timezone.localdate, verbose_name='fecha de surtido')),
                ('notas', models.TextField(blank=True, verbose_name='notas')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='surtidos', to='pedidos.pedido', verbose_name='pedido')),
                ('surtido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surtidos_realizados', to=settings.AUTH_USER_MODEL, verbose_name='surtido por')),
            ],
            options={
                'verbose_name': 'surtido',
                'verbose_name_plural': 'surtidos',
                'ordering': ['-fecha_surtido'],
            },
        ),
        migrations.CreateModel(
            name='SurtidoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('cantidad_surtida', models.DecimalField(decimal_places=3, help_text='Siempre positiva; el signo negativo se aplica al movimiento de inventario.', max_digits=12, verbose_name='cantidad surtida')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='surtidos', to='inventario.lote', verbose_name='lote')),
                ('pedido_detalle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='surtidos', to='pedidos.pedidodetalle', verbose_name='detalle de pedido')),
                ('surtido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='pedidos.surtido', verbose_name='surtido')),
            ],
            options={
                'verbose_name': 'detalle de surtido',
                'verbose_name_plural': 'detalles de surtido',
                'ordering': ['surtido', 'pedido_detalle'],
            },
        ),
        migrations.AddConstraint(
            model_name='pedidodetalle',
            constraint=models.UniqueConstraint(fields=('pedido', 'producto'), name='pedido_detalle_unico'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['ruta', 'activo'], name='pedidos_cli_ruta_id_cb7931_idx'),
        ),
    ]
