# Generated by Django 6.0.7 on 2026-07-31 21:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('folio', models.CharField(blank=True, help_text='Se genera solo al guardar por primera vez. No editar después.', max_length=20, verbose_name='folio')),
                ('fecha_emision', models.DateField(default=django.utils.timezone.localdate, verbose_name='fecha de emisión')),
                ('fecha_entrega_estimada', models.DateField(blank=True, null=True, verbose_name='fecha de entrega estimada')),
                ('estatus', models.CharField(choices=[('borrador', 'Borrador'), ('enviada', 'Enviada'), ('confirmada', 'Confirmada'), ('recibida_parcial', 'Recibida parcial'), ('recibida', 'Recibida'), ('cancelada', 'Cancelada')], default='borrador', max_length=20, verbose_name='estatus')),
                ('moneda', models.CharField(default='MXN', max_length=3, verbose_name='moneda')),
                ('notas', models.TextField(blank=True, verbose_name='notas')),
            ],
            options={
                'verbose_name': 'orden de compra',
                'verbose_name_plural': 'órdenes de compra',
                'ordering': ['-fecha_emision', '-folio'],
            },
        ),
        migrations.CreateModel(
            name='OrdenCompraDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('cantidad_pedida', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='cantidad pedida')),
                ('unidad_compra', models.CharField(choices=[('caja', 'Caja'), ('pieza', 'Pieza'), ('kilogramo', 'Kilogramo')], max_length=10, verbose_name='unidad de compra')),
                ('unidades_por_caja', models.PositiveIntegerField(help_text='Fotografía al momento del pedido; no se actualiza si cambia después.', verbose_name='unidades por caja')),
                ('costo_unitario', models.DecimalField(decimal_places=2, help_text='Fotografía al momento del pedido.', max_digits=10, verbose_name='costo unitario')),
            ],
            options={
                'verbose_name': 'detalle de orden de compra',
                'verbose_name_plural': 'detalles de orden de compra',
                'ordering': ['orden', 'producto'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('nombre', models.CharField(max_length=150, verbose_name='nombre')),
                ('razon_social', models.CharField(blank=True, max_length=200, verbose_name='razón social')),
                ('rfc', models.CharField(blank=True, max_length=13, verbose_name='RFC')),
                ('contacto', models.CharField(blank=True, max_length=150, verbose_name='contacto')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='correo')),
                ('direccion', models.TextField(blank=True, verbose_name='dirección')),
                ('dias_entrega_estimados', models.PositiveSmallIntegerField(verbose_name='días de entrega estimados')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'verbose_name': 'proveedor',
                'verbose_name_plural': 'proveedores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ProveedorProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('sku_proveedor', models.CharField(blank=True, max_length=50, verbose_name='SKU del proveedor')),
                ('costo_actual', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='costo actual')),
                ('unidades_por_caja', models.PositiveIntegerField(verbose_name='unidades por caja')),
                ('pedido_minimo', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='pedido mínimo')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'verbose_name': 'producto de proveedor',
                'verbose_name_plural': 'productos de proveedor',
                'ordering': ['proveedor', 'producto'],
            },
        ),
        migrations.CreateModel(
            name='Recepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('fecha_recepcion', models.DateField(default=django.utils.timezone.localdate, verbose_name='fecha de recepción')),
                ('folio_factura', models.CharField(blank=True, max_length=50, verbose_name='folio de factura')),
                ('notas', models.TextField(blank=True, verbose_name='notas')),
            ],
            options={
                'verbose_name': 'recepción',
                'verbose_name_plural': 'recepciones',
                'ordering': ['-fecha_recepcion'],
            },
        ),
        migrations.CreateModel(
            name='RecepcionDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('cantidad_recibida', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='cantidad recibida')),
                ('fecha_caducidad', models.DateField(verbose_name='fecha de caducidad')),
                ('codigo_lote_proveedor', models.CharField(blank=True, max_length=50, verbose_name='código de lote del proveedor')),
                ('costo_unitario_real', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='costo unitario real')),
            ],
            options={
                'verbose_name': 'detalle de recepción',
                'verbose_name_plural': 'detalles de recepción',
                'ordering': ['recepcion', 'orden_detalle'],
            },
        ),
    ]
