# Generated by Django 6.0.7 on 2026-07-31 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0004_alter_producto_vida_anaquel'),
        ('compras', '0001_initial'),
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='almacen_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_compra', to='inventario.almacen', verbose_name='almacén destino'),
        ),
        migrations.AddField(
            model_name='ordencompradetalle',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='compras.ordencompra', verbose_name='orden'),
        ),
        migrations.AddField(
            model_name='ordencompradetalle',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_orden_compra', to='catalogo.producto', verbose_name='producto'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_compra', to='compras.proveedor', verbose_name='proveedor'),
        ),
        migrations.AddField(
            model_name='proveedorproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proveedores_producto', to='catalogo.producto', verbose_name='producto'),
        ),
        migrations.AddField(
            model_name='proveedorproducto',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_ofrecidos', to='compras.proveedor', verbose_name='proveedor'),
        ),
        migrations.AddField(
            model_name='recepcion',
            name='orden_compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recepciones', to='compras.ordencompra', verbose_name='orden de compra'),
        ),
        migrations.AddField(
            model_name='recepcion',
            name='recibido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recepciones_recibidas', to=settings.AUTH_USER_MODEL, verbose_name='recibido por'),
        ),
        migrations.AddField(
            model_name='recepciondetalle',
            name='orden_detalle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recepciones', to='compras.ordencompradetalle', verbose_name='detalle de orden'),
        ),
        migrations.AddField(
            model_name='recepciondetalle',
            name='recepcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='compras.recepcion', verbose_name='recepción'),
        ),
        migrations.AddConstraint(
            model_name='ordencompradetalle',
            constraint=models.UniqueConstraint(fields=('orden', 'producto'), name='orden_compra_detalle_unico'),
        ),
        migrations.AddConstraint(
            model_name='proveedorproducto',
            constraint=models.UniqueConstraint(fields=('proveedor', 'producto'), name='proveedor_producto_unico'),
        ),
    ]
