# Generated by Django 6.0.7 on 2026-08-14 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompradetalle',
            name='cerrado',
            field=models.BooleanField(default=False, help_text='Lo que faltó de esta línea ya no va a llegar; deja de contar como pendiente.', verbose_name='cerrado'),
        ),
        migrations.AddField(
            model_name='ordencompradetalle',
            name='cerrado_en',
            field=models.DateTimeField(blank=True, null=True, verbose_name='cerrado en'),
        ),
        migrations.AddField(
            model_name='ordencompradetalle',
            name='cerrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineas_compra_cerradas', to=settings.AUTH_USER_MODEL, verbose_name='cerrado por'),
        ),
        migrations.AddField(
            model_name='ordencompradetalle',
            name='motivo_faltante',
            field=models.CharField(blank=True, choices=[('no_surtido', 'No lo surtió el proveedor'), ('agotado', 'Agotado con el proveedor'), ('calidad', 'Rechazado por calidad'), ('cancelado', 'Cancelado por nosotros')], max_length=20, verbose_name='motivo del faltante'),
        ),
        migrations.AddField(
            model_name='ordencompradetalle',
            name='notas_faltante',
            field=models.CharField(blank=True, max_length=255, verbose_name='notas del faltante'),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='estatus',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('enviada', 'Enviada'), ('confirmada', 'Confirmada'), ('recibida_parcial', 'Recibida parcial'), ('recibida', 'Recibida'), ('cerrada_incompleta', 'Cerrada con faltante'), ('cancelada', 'Cancelada')], default='borrador', max_length=20, verbose_name='estatus'),
        ),
    ]
